[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"

gas_reports = ["*"]
no_test = true


[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base_sepolia = { key = "${BASE_ETHERSCAN_API_KEY}" }

[fmt] # See https://book.getfoundry.sh/reference/config/formatter
int_types = "short"
line_length = 120
bracket_spacing = true
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "single"
ignore = ['./script/**/*']


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
